// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"bookstore-operator/pkg/apis/blog/v1alpha1.BookStore":       schema_pkg_apis_blog_v1alpha1_BookStore(ref),
		"bookstore-operator/pkg/apis/blog/v1alpha1.BookStoreSpec":   schema_pkg_apis_blog_v1alpha1_BookStoreSpec(ref),
		"bookstore-operator/pkg/apis/blog/v1alpha1.BookStoreStatus": schema_pkg_apis_blog_v1alpha1_BookStoreStatus(ref),
	}
}

func schema_pkg_apis_blog_v1alpha1_BookStore(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BookStore is the Schema for the bookstores API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("bookstore-operator/pkg/apis/blog/v1alpha1.BookStoreSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("bookstore-operator/pkg/apis/blog/v1alpha1.BookStoreStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"bookstore-operator/pkg/apis/blog/v1alpha1.BookStoreSpec", "bookstore-operator/pkg/apis/blog/v1alpha1.BookStoreStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_blog_v1alpha1_BookStoreSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BookStoreSpec defines the desired state of BookStore",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_blog_v1alpha1_BookStoreStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BookStoreStatus defines the observed state of BookStore",
				Type:        []string{"object"},
			},
		},
	}
}
