// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookApp) DeepCopyInto(out *BookApp) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BookApp.
func (in *BookApp) DeepCopy() *BookApp {
	if in == nil {
		return nil
	}
	out := new(BookApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookDB) DeepCopyInto(out *BookDB) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BookDB.
func (in *BookDB) DeepCopy() *BookDB {
	if in == nil {
		return nil
	}
	out := new(BookDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookStore) DeepCopyInto(out *BookStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BookStore.
func (in *BookStore) DeepCopy() *BookStore {
	if in == nil {
		return nil
	}
	out := new(BookStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BookStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookStoreList) DeepCopyInto(out *BookStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BookStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BookStoreList.
func (in *BookStoreList) DeepCopy() *BookStoreList {
	if in == nil {
		return nil
	}
	out := new(BookStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BookStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookStoreSpec) DeepCopyInto(out *BookStoreSpec) {
	*out = *in
	out.BookApp = in.BookApp
	out.BookDB = in.BookDB
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BookStoreSpec.
func (in *BookStoreSpec) DeepCopy() *BookStoreSpec {
	if in == nil {
		return nil
	}
	out := new(BookStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BookStoreStatus) DeepCopyInto(out *BookStoreStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BookStoreStatus.
func (in *BookStoreStatus) DeepCopy() *BookStoreStatus {
	if in == nil {
		return nil
	}
	out := new(BookStoreStatus)
	in.DeepCopyInto(out)
	return out
}
