apiVersion: blog.velotio.com/v1alpha1
kind: BookStore
metadata:
  name: example-bookstore
spec:
  bookApp: 
    repository: "akash125/pyapp"
    tag: latest
    imagePullPolicy: "IfNotPresent"
    replicas: 1
    port: 80
    targetPort: 3000
    serviceType: "LoadBalancer"
  bookDB:
    repository: mongo
    tag: latest
    imagePullPolicy: "IfNotPresent"
    replicas: 1
    port: 27017
    dbSize: 2Gi

  
