apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bookstore-operator
  template:
    metadata:
      labels:
        name: bookstore-operator
    spec:
      serviceAccountName: bookstore-operator
      containers:
        - name: bookstore-operator
          # Replace this with the built image name
          image: akash125/bookstore-operator:golang
          command:
          - bookstore-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bookstore-operator"
